name: Xcode CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Build with Xcode
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
